/**
 * Oracle Presets — extracted from oracleStore for modularity
 */
import type { OracleMode, OraclePreset } from '../types/oracleTypes';

export const ORACLE_MODES: Record<
  OracleMode,
  { label: string; icon: string; description: string; stages: string[] }
> = {
  council: {
    label: 'Conselho',
    icon: '🏛️',
    description: 'N modelos + peer review + síntese — padrão Karpathy',
    stages: ['Opiniões', 'Peer Review', 'Síntese'],
  },
  researcher: {
    label: 'Pesquisador',
    icon: '🔬',
    description: 'Pesquisa profunda multi-fonte com relatório estruturado',
    stages: ['Decomposição', 'Análise', 'Síntese', 'Verificação'],
  },
  validator: {
    label: 'Validador',
    icon: '✅',
    description: 'Verifica claims contra múltiplos modelos',
    stages: ['Verificação', 'Cruzamento', 'Veredicto'],
  },
  executor: {
    label: 'Executor',
    icon: '⚡',
    description: 'Decompõe tarefa em sub-tarefas e orquestra execução',
    stages: ['Planejamento', 'Execução', 'Consolidação'],
  },
  advisor: {
    label: 'Conselheiro',
    icon: '🎯',
    description: 'Debate estruturado com prós/contras para decisões',
    stages: ['Análise', 'Debate', 'Recomendação'],
  },
};

export const ORACLE_PRESETS: OraclePreset[] = [
  {
    id: 'executive',
    name: '👔 Conselho Executivo',
    icon: '👔',
    description: 'Decisões estratégicas com múltiplas perspectivas de liderança',
    mode: 'council',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Analista Estratégico' },
      { model: 'openai/gpt-5', persona: 'Consultor de Negócios' },
      { model: 'google/gemini-2.5-flash', persona: 'Especialista em Dados' },
    ],
    chairman: 'google/gemini-2.5-pro',
    enablePeerReview: true,
    enableThinking: false,
  },
  {
    id: 'quick',
    name: '⚡ Oráculo Rápido',
    icon: '⚡',
    description: 'Respostas rápidas com 2 modelos e sem peer review',
    mode: 'council',
    members: [
      { model: 'google/gemini-2.5-flash', persona: 'Assistente Rápido' },
      { model: 'openai/gpt-5-mini', persona: 'Analista' },
    ],
    chairman: 'google/gemini-2.5-flash',
    enablePeerReview: false,
    enableThinking: false,
  },
  {
    id: 'technical',
    name: '💻 Arquitetura Técnica',
    icon: '💻',
    description: 'Decisões de arquitetura, tech stack, code review',
    mode: 'council',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Arquiteto Senior focado em escalabilidade' },
      { model: 'openai/gpt-5', persona: 'Especialista em segurança e edge cases' },
      { model: 'google/gemini-2.5-flash', persona: 'Pesquisador de melhores práticas' },
    ],
    chairman: 'google/gemini-2.5-pro',
    enablePeerReview: true,
    enableThinking: true,
  },
  {
    id: 'debate',
    name: '⚖️ Debate de Decisão',
    icon: '⚖️',
    description: 'Debate estruturado com prós e contras',
    mode: 'advisor',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Defensor (a favor)' },
      { model: 'openai/gpt-5', persona: 'Oponente (contra)' },
      { model: 'google/gemini-2.5-flash', persona: 'Mediador neutro' },
    ],
    chairman: 'google/gemini-2.5-flash',
    enablePeerReview: true,
    enableThinking: false,
  },
  {
    id: 'financial_analysis',
    name: '💰 Análise Financeira',
    icon: '💰',
    description: 'Decisões financeiras com projeções e análise de risco',
    mode: 'advisor',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Analista Financeiro Senior' },
      { model: 'openai/gpt-5', persona: 'Controller e Gestor de Riscos' },
      { model: 'google/gemini-2.5-flash', persona: 'Especialista em Projeções' },
    ],
    chairman: 'google/gemini-2.5-pro',
    enablePeerReview: true,
    enableThinking: true,
    criteriaWeights: { accuracy: 30, reasoning: 25, practicality: 25, risk_assessment: 20 },
  },
  {
    id: 'market_research',
    name: '🔬 Pesquisa de Mercado',
    icon: '🔬',
    description: 'Análise profunda de mercado com fontes verificáveis',
    mode: 'researcher',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Pesquisador de Mercado' },
      { model: 'openai/gpt-5', persona: 'Analista de Tendências' },
      { model: 'google/gemini-2.5-flash', persona: 'Coletor de Dados' },
    ],
    chairman: 'google/gemini-2.5-pro',
    enablePeerReview: true,
    enableThinking: true,
  },
  {
    id: 'factcheck',
    name: '🔍 Verificação de Fatos',
    icon: '🔍',
    description: 'Verifica claims contra múltiplos modelos',
    mode: 'validator',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Verificador de Fatos' },
      { model: 'openai/gpt-5', persona: 'Analista Crítico' },
      { model: 'google/gemini-2.5-flash', persona: 'Pesquisador de Fontes' },
    ],
    chairman: 'google/gemini-2.5-pro',
    enablePeerReview: true,
    enableThinking: false,
  },
  {
    id: 'legal_compliance',
    name: '⚖️ Jurídico & Compliance',
    icon: '⚖️',
    description: 'Análise jurídica com múltiplas perspectivas e legislação',
    mode: 'validator',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Consultor Jurídico' },
      { model: 'openai/gpt-5', persona: 'Especialista em Compliance' },
      { model: 'google/gemini-2.5-flash', persona: 'Pesquisador de Legislação' },
    ],
    chairman: 'google/gemini-2.5-pro',
    enablePeerReview: true,
    enableThinking: true,
  },
  {
    id: 'crisis_response',
    name: '🚨 Resposta a Crise',
    icon: '🚨',
    description: 'Decisão rápida em situação crítica — sem peer review',
    mode: 'council',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Gestor de crise focado em ação imediata' },
      { model: 'openai/gpt-5', persona: 'Analista de riscos e consequências' },
      { model: 'google/gemini-2.5-flash', persona: 'Comunicador — stakeholders' },
    ],
    chairman: 'google/gemini-2.5-pro',
    enablePeerReview: false,
    enableThinking: false,
  },
  {
    id: 'content_strategy',
    name: '✍️ Estratégia de Conteúdo',
    icon: '✍️',
    description: 'Brainstorming criativo com múltiplas perspectivas',
    mode: 'council',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Estrategista de marca' },
      { model: 'openai/gpt-5', persona: 'Copywriter criativo e storyteller' },
      { model: 'google/gemini-2.5-flash', persona: 'Analista de tendências e SEO' },
    ],
    chairman: 'openai/gpt-5',
    enablePeerReview: true,
    enableThinking: false,
  },
  {
    id: 'hr_people',
    name: '👥 RH & Pessoas',
    icon: '👥',
    description: 'Decisões sobre pessoas, cultura e desenvolvimento',
    mode: 'advisor',
    members: [
      { model: 'google/gemini-2.5-pro', persona: 'Diretor de RH' },
      { model: 'openai/gpt-5', persona: 'Especialista em Cultura Organizacional' },
      { model: 'google/gemini-2.5-flash', persona: 'Analista de Desenvolvimento' },
    ],
    chairman: 'google/gemini-2.5-pro',
    enablePeerReview: true,
    enableThinking: false,
  },
];
