export interface Agent {
  id: string; name: string; description: string; type: string; model: string;
  status: 'active' | 'draft' | 'paused' | 'error'; owner: string; tags: string[];
  sessions24h: number; avgLatency: number; costToday: number; successRate: number;
  satisfaction: number; tokensIn: number; tokensOut: number; toolCalls: number;
  maturity: 'prototype' | 'tested' | 'production'; createdAt: string; updatedAt: string;
}

export const agents: Agent[] = [
  { id: '1', name: 'Atlas — Atendimento Premium', description: 'Agente de suporte L1/L2 com acesso a base de conhecimento técnica e CRM', type: 'Suporte', model: 'GPT-4o', status: 'active', owner: 'Marina Costa', tags: ['suporte', 'CRM', 'RAG'], sessions24h: 1247, avgLatency: 1.8, costToday: 42.30, successRate: 94.2, satisfaction: 4.7, tokensIn: 580000, tokensOut: 320000, toolCalls: 890, maturity: 'production', createdAt: '2025-11-15', updatedAt: '2026-03-28' },
  { id: '2', name: 'Scout — Pesquisador de Mercado', description: 'Agente de pesquisa com web search, browser e análise de documentos', type: 'Pesquisador', model: 'Claude 3.5 Sonnet', status: 'active', owner: 'Rafael Mendes', tags: ['pesquisa', 'web', 'análise'], sessions24h: 342, avgLatency: 3.2, costToday: 28.50, successRate: 89.5, satisfaction: 4.5, tokensIn: 420000, tokensOut: 280000, toolCalls: 560, maturity: 'tested', createdAt: '2026-01-08', updatedAt: '2026-03-29' },
  { id: '3', name: 'Cleo — SDR Inteligente', description: 'Agente de prospecção outbound com integração a CRM, email e calendário', type: 'SDR', model: 'GPT-4o', status: 'active', owner: 'Juliana Santos', tags: ['vendas', 'email', 'CRM'], sessions24h: 523, avgLatency: 2.1, costToday: 35.80, successRate: 78.3, satisfaction: 4.2, tokensIn: 310000, tokensOut: 190000, toolCalls: 1240, maturity: 'production', createdAt: '2025-12-01', updatedAt: '2026-03-30' },
  { id: '4', name: 'Sentinel — Compliance Analyst', description: 'Agente de análise regulatória e due diligence com RAG jurídico', type: 'Analista', model: 'Claude 3.5 Sonnet', status: 'active', owner: 'Bruno Almeida', tags: ['compliance', 'legal', 'RAG'], sessions24h: 89, avgLatency: 4.5, costToday: 18.90, successRate: 96.1, satisfaction: 4.8, tokensIn: 290000, tokensOut: 180000, toolCalls: 120, maturity: 'tested', createdAt: '2026-02-14', updatedAt: '2026-03-27' },
  { id: '5', name: 'Orchestrator — Multiagente Hub', description: 'Orquestrador que coordena sub-agentes para tarefas complexas', type: 'Orquestrador', model: 'GPT-4o', status: 'draft', owner: 'Marina Costa', tags: ['multiagent', 'workflow', 'orquestração'], sessions24h: 0, avgLatency: 0, costToday: 0, successRate: 0, satisfaction: 0, tokensIn: 0, tokensOut: 0, toolCalls: 0, maturity: 'prototype', createdAt: '2026-03-25', updatedAt: '2026-03-29' },
  { id: '6', name: 'Iris — BI Analyst', description: 'Agente de análise de dados com SQL, visualizações e relatórios automatizados', type: 'Analista', model: 'Gemini 1.5 Pro', status: 'paused', owner: 'Carlos Ferreira', tags: ['BI', 'SQL', 'dados'], sessions24h: 0, avgLatency: 2.8, costToday: 0, successRate: 85.7, satisfaction: 4.3, tokensIn: 0, tokensOut: 0, toolCalls: 0, maturity: 'tested', createdAt: '2026-01-20', updatedAt: '2026-03-15' },
  { id: '7', name: 'Nova — Copiloto Dev', description: 'Assistente de desenvolvimento com code execution, documentação e debugging', type: 'Copiloto', model: 'Claude 3.5 Sonnet', status: 'error', owner: 'Rafael Mendes', tags: ['dev', 'código', 'debugging'], sessions24h: 15, avgLatency: 5.1, costToday: 8.20, successRate: 62.0, satisfaction: 3.8, tokensIn: 95000, tokensOut: 75000, toolCalls: 340, maturity: 'prototype', createdAt: '2026-03-10', updatedAt: '2026-03-30' },
];
